### ISSUE TITLE
Music not playing

### ISSUE THREAD

**Issue by aaronrai24** [aaronrai24/DollarDiscordBot#101]
Bug report: No error logs from dollar/lavalink, able to queue song correctly but no audio plays...

Submitted by: mfcash
Server: mfDiscord

**Comment by aaronrai24** [comment]
Was able to use: https://github.com/lavalink-devs/youtube-source#plugin

```yml
plugins:
  youtube:
    enabled: true
    clients: ["MUSIC", "ANDROID", "WEB"]
lavalink:
  plugins:
    # Replace VERSION with the current version as shown by the Releases tab or a long commit hash for snapshots.
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.1.0"
      repository: "https://maven.lavalink.dev/releases" # use https://maven.lavalink.dev/snapshots if you want to use a snapshot version.
```
